export as namespace Ranvier;

import Account = require("./Account");
import AccountManager = require("./AccountManager");
import * as Ansi from "./Ansi";
import Area = require("./Area");
import AreaAudience = require("./AreaAudience");
import AreaFactory = require("./AreaFactory");
import AreaFloor = require("./AreaFloor");
import AreaManager = require("./AreaManager");
import * as Attribute from "./Attribute";
import AttributeFactory = require("./AttributeFactory");
import Attributes = require("./Attributes");
import BehaviorManager = require("./BehaviorManager");
import Broadcast = require("./Broadcast");
import BundleManager = require("./BundleManager");
import * as Channel from "./Channel";
import ChannelAudience = require("./ChannelAudience");
import ChannelManager = require("./ChannelManager");
import Character = require("./Character");
import Command = require("./Command");
import CommandManager = require("./CommandManager");
import CommandQueue = require("./CommandQueue");
import CommandType = require("./CommandType");
import Config = require("./Config");
import Damage = require("./Damage");
import Data = require("./Data");
import DataSourceRegistry = require("./DataSourceRegistry");
import Effect = require("./Effect");
import EffectFactory = require("./EffectFactory");
import EffectFlag = require("./EffectFlag");
import EffectList = require("./EffectList");
import EntityFactory = require("./EntityFactory");
import EntityLoader = require("./EntityLoader");
import EntityLoaderRegistry = require("./EntityLoaderRegistry");
import * as EquipErrors from "./EquipErrors";
import EventManager = require("./EventManager");
import EventUtil = require("./EventUtil");
import GameEntity = require("./GameEntity");
import GameServer = require("./GameServer");
import Heal = require("./Heal");
import HelpManager = require("./HelpManager");
import Helpfile = require("./Helpfile");
import * as Inventory from "./Inventory";
import Item = require("./Item");
import ItemFactory = require("./ItemFactory");
import ItemManager = require("./ItemManager");
import ItemType = require("./ItemType");
import Logger = require("./Logger");
import Metadatable = require("./Metadatable");
import MobFactory = require("./MobFactory");
import MobManager = require("./MobManager");
import Npc = require("./Npc");
import Party = require("./Party");
import PartyAudience = require("./PartyAudience");
import PartyManager = require("./PartyManager");
import Player = require("./Player");
import PlayerManager = require("./PlayerManager");
import PlayerRoles = require("./PlayerRoles");
import PrivateAudience = require("./PrivateAudience");
import Quest = require("./Quest");
import QuestFactory = require("./QuestFactory");
import QuestGoal = require("./QuestGoal");
import QuestGoalManager = require("./QuestGoalManager");
import QuestReward = require("./QuestReward");
import QuestRewardManager = require("./QuestRewardManager");
import QuestTracker = require("./QuestTracker");
import RoleAudience = require("./RoleAudience");
import Room = require("./Room");
import RoomAudience = require("./RoomAudience");
import RoomFactory = require("./RoomFactory");
import RoomManager = require("./RoomManager");
import Scriptable = require("./Scriptable");
import Skill = require("./Skill");
import * as SkillErrors from "./SkillErrors";
import SkillFlag = require("./SkillFlag");
import SkillManager = require("./SkillManager");
import SkillType = require("./SkillType");
import TransportStream = require("./TransportStream");
import * as Util from "./Util";
import WorldAudience = require("./WorldAudience");
import type { Broadcastable as BroadcastableType, BroadcastTarget as BroadcastTargetType } from "./Broadcastable";

declare const ranvier: {
  Account: typeof Account;
  AccountManager: typeof AccountManager;
  Ansi: typeof Ansi;
  Area: typeof Area;
  AreaAudience: typeof AreaAudience;
  AreaFactory: typeof AreaFactory;
  AreaFloor: typeof AreaFloor;
  AreaManager: typeof AreaManager;
  Attribute: typeof Attribute;
  AttributeFactory: typeof AttributeFactory;
  Attributes: typeof Attributes;
  BehaviorManager: typeof BehaviorManager;
  Broadcast: typeof Broadcast;
  BundleManager: typeof BundleManager;
  Channel: typeof Channel;
  ChannelAudience: typeof ChannelAudience;
  ChannelManager: typeof ChannelManager;
  Character: typeof Character;
  Command: typeof Command;
  CommandManager: typeof CommandManager;
  CommandQueue: typeof CommandQueue;
  CommandType: typeof CommandType;
  Config: typeof Config;
  Damage: typeof Damage;
  Data: typeof Data;
  DataSourceRegistry: typeof DataSourceRegistry;
  Effect: typeof Effect;
  EffectFactory: typeof EffectFactory;
  EffectFlag: typeof EffectFlag;
  EffectList: typeof EffectList;
  EntityFactory: typeof EntityFactory;
  EntityLoader: typeof EntityLoader;
  EntityLoaderRegistry: typeof EntityLoaderRegistry;
  EquipErrors: typeof EquipErrors;
  EventManager: typeof EventManager;
  EventUtil: typeof EventUtil;
  GameEntity: typeof GameEntity;
  GameServer: typeof GameServer;
  Heal: typeof Heal;
  HelpManager: typeof HelpManager;
  Helpfile: typeof Helpfile;
  Inventory: typeof Inventory;
  Item: typeof Item;
  ItemFactory: typeof ItemFactory;
  ItemManager: typeof ItemManager;
  ItemType: typeof ItemType;
  Logger: typeof Logger;
  Metadatable: typeof Metadatable;
  MobFactory: typeof MobFactory;
  MobManager: typeof MobManager;
  Npc: typeof Npc;
  Party: typeof Party;
  PartyAudience: typeof PartyAudience;
  PartyManager: typeof PartyManager;
  Player: typeof Player;
  PlayerManager: typeof PlayerManager;
  PlayerRoles: typeof PlayerRoles;
  PrivateAudience: typeof PrivateAudience;
  Quest: typeof Quest;
  QuestFactory: typeof QuestFactory;
  QuestGoal: typeof QuestGoal;
  QuestGoalManager: typeof QuestGoalManager;
  QuestReward: typeof QuestReward;
  QuestRewardManager: typeof QuestRewardManager;
  QuestTracker: typeof QuestTracker;
  RoleAudience: typeof RoleAudience;
  Room: typeof Room;
  RoomAudience: typeof RoomAudience;
  RoomFactory: typeof RoomFactory;
  RoomManager: typeof RoomManager;
  Scriptable: typeof Scriptable;
  Skill: typeof Skill;
  SkillErrors: typeof SkillErrors;
  SkillFlag: typeof SkillFlag;
  SkillManager: typeof SkillManager;
  SkillType: typeof SkillType;
  TransportStream: typeof TransportStream;
  Util: typeof Util;
  WorldAudience: typeof WorldAudience;
};

declare namespace ranvier {
  type BroadcastTarget = BroadcastTargetType;
  type Broadcastable<TTarget extends BroadcastTarget = BroadcastTarget> = BroadcastableType<TTarget>;
}

export = ranvier;
